name: ariadne_cpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.7.*
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pyyaml=5.3.1
  - pandas=1.1.1
  - scikit-learn=0.23.2
  - nose=1.3.7
  - networkx=2.5
  - jupyter=1.0.0
  - notebook=6.1.3
  - torchvision=0.7.0
  - cpuonly=1.0
  - pytorch=1.6.0
  - pyqt=5.12.*
  - vispy=0.6.4
  - pytorch-lightning=0.9.0
  - gin-config=0.3.0
  - absl-py=0.9.0
  - pylint=2.6.0
  - pytest
  - pip:
      - torch-geometric==1.6.1
      - torch-scatter==2.0.5
      - torch-sparse==0.6.8
      - torch-spline-conv==1.2.0


