name: ariadne_gpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - pyyaml
  - pandas
  - scikit-learn
  - nose
  - pytables
  - memory_profiler
  - notebook
  - torchvision
  - cudatoolkit=10.1
  - pytorch
  - pytorch-lightning
  - gin-config
  - absl-py
  - faiss
  - pip
  - pip:
      - pyqt5==5.15.*
      - matplotlib