name: ariadne_cpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - matplotlib
  - pyyaml
  - pandas
  - seaborn
  - ipywidgets
  - scikit-learn
  - h5py<3.2
  - nose=1.3.7
  - notebook
  - torchvision
  - cpuonly=1.0
  - pytorch
  - pyqt=5.12.*
  - pytorch-lightning
  - torchmetrics
  - gin-config
  - absl-py
  - faiss
