name: ariadne_gpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.7.*
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pyyaml=5.3.1
  - pandas=1.1.1
  - scikit-learn=0.23.2
  - nose=1.3.7
  - networkx=2.5
  - jupyter=1.0.0
  - seaborn
  - notebook=6.1.3
  - torchvision=0.7.0
  - cudatoolkit=10.1
  - pytorch=1.6.0
  - vispy=0.6.4
  - pytorch-lightning=0.9.0
  - gin-config=0.3.0
  - absl-py=0.9.0
  - pylint=2.6.0
  - pytest
  - pip
  - pip:
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1


